"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from urllib.parse import quote_plus

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, this should be set via environment variable
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-k0c(80w%a#!4sojsrk2&1ft$-=8cl-^l-)58)@iipif*$p#%o%')

# SECURITY WARNING: don't run with debug turned on in production!
# Base settings default to DEBUG=True for development
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Base allowed hosts for development
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '10.0.2.2',  # Android emulator's special IP to access host machine
]

# Add any additional hosts from environment variable
if os.getenv('ALLOWED_HOSTS'):
    ALLOWED_HOSTS.extend([host.strip() for host in os.getenv('ALLOWED_HOSTS').split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'apps.sanatan_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware should be as high as possible
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Get database configuration from environment variables
DB_USER = os.getenv('DB_USER') or os.getenv('user')
DB_PASSWORD = os.getenv('DB_PASSWORD') or os.getenv('password')
DB_HOST = os.getenv('DB_HOST') or os.getenv('host')
DB_PORT = os.getenv('DB_PORT') or os.getenv('port') or '5432'
DB_NAME = os.getenv('DB_NAME') or os.getenv('dbname')
DATABASE_URL = os.getenv('DATABASE_URL')

# Configure database
if DATABASE_URL:
    # Use DATABASE_URL if provided
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.parse(DATABASE_URL)
        }
    except ImportError:
        # Fallback if dj-database-url is not installed
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
elif all([DB_USER, DB_PASSWORD, DB_HOST, DB_NAME]):
    # Construct from individual components
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'sslmode': 'require' if 'supabase.co' in DB_HOST or 'supabase.com' in DB_HOST else None,
            },
        }
    }
else:
    # Fallback to SQLite for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.services.authentication.UUIDJWTAuthentication',
    ],
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Sanatan App API',
    'DESCRIPTION': 'Backend API for Sanatan App - Hindu Mythology Knowledge',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ORIGINS', '*') == '*'
CORS_ALLOWED_ORIGINS = [
    origin.strip() 
    for origin in os.getenv('CORS_ORIGINS', '').split(',') 
    if origin.strip() and origin.strip() != '*'
] if os.getenv('CORS_ORIGINS') and os.getenv('CORS_ORIGINS') != '*' else []

CORS_ALLOW_CREDENTIALS = not CORS_ALLOW_ALL_ORIGINS

# Groq API Key
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Access token expires in 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # Refresh token expires in 30 days
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Process one task at a time

# Celery Beat Configuration (for scheduled tasks)
# These are periodic tasks that will be executed by Celery Beat scheduler
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Daily at 5 AM: QA for existing Shlokas (matches architecture diagram)
    # Flow: QA → If not good enough → Groq → QA again → Save to DB
    'qa-existing-shlokas-daily': {
        'task': 'sanatan_app.batch_qa_existing_shlokas',
        'schedule': crontab(hour=5, minute=0),  # Run daily at 5 AM UTC (as per architecture)
        'args': (100, 70),  # max_shlokas=100, quality_threshold=70
    },
    # Daily: Check quality of explanations that have never been checked (supplementary)
    'check-unchecked-explanations-daily': {
        'task': 'sanatan_app.batch_check_shlokas_quality',
        'schedule': crontab(hour=2, minute=0),  # Run daily at 2 AM UTC
        'args': (100, True, None, None, None),  # max_shlokas=100, never_checked=True
    },
    # Weekly: Improve low-quality explanations (supplementary)
    'improve-low-quality-explanations-weekly': {
        'task': 'sanatan_app.batch_improve_shlokas',
        'schedule': crontab(hour=3, minute=0, day_of_week=0),  # Run weekly on Sunday at 3 AM UTC
        'args': (50, 70, 3, 70),  # max_shlokas=50, max_score_threshold=70, max_iterations=3, min_score_threshold=70
    },
    # Monthly: Re-check explanations checked more than 30 days ago (supplementary)
    'recheck-old-explanations-monthly': {
        'task': 'sanatan_app.batch_check_shlokas_quality',
        'schedule': crontab(hour=4, minute=0, day_of_month=1),  # Run monthly on 1st at 4 AM UTC
        'args': (200, False, 30, None, None),  # max_shlokas=200, never_checked=False, checked_before_days=30
    },
}
