# Generated by Django 4.2.26 on 2025-11-24 21:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_type', models.CharField(choices=[('summary', 'Summary'), ('detailed', 'Detailed')], max_length=20)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reading_logs',
            },
        ),
        migrations.CreateModel(
            name='Shloka',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_name', models.TextField()),
                ('chapter_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('verse_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sanskrit_text', models.TextField()),
                ('transliteration', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shlokas',
                'ordering': ['book_name', 'chapter_number', 'verse_number'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ShlokaExplanation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('explanation_type', models.CharField(choices=[('summary', 'Summary'), ('detailed', 'Detailed')], max_length=20)),
                ('explanation_text', models.TextField()),
                ('ai_model_used', models.TextField(blank=True, null=True)),
                ('generation_prompt', models.TextField(blank=True, null=True)),
                ('shloka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='sanatan_app.shloka')),
            ],
            options={
                'db_table': 'shloka_explanations',
            },
        ),
        migrations.AddIndex(
            model_name='shloka',
            index=models.Index(fields=['book_name', 'chapter_number', 'verse_number'], name='shlokas_book_na_742637_idx'),
        ),
        migrations.AddField(
            model_name='readinglog',
            name='shloka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_logs', to='sanatan_app.shloka'),
        ),
        migrations.AddField(
            model_name='readinglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_logs', to='sanatan_app.user'),
        ),
        migrations.AddIndex(
            model_name='shlokaexplanation',
            index=models.Index(fields=['shloka', 'explanation_type'], name='shloka_expl_shloka__f9555d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shlokaexplanation',
            unique_together={('shloka', 'explanation_type')},
        ),
        migrations.AddIndex(
            model_name='readinglog',
            index=models.Index(fields=['user', 'read_at'], name='reading_log_user_id_284d34_idx'),
        ),
        migrations.AddIndex(
            model_name='readinglog',
            index=models.Index(fields=['shloka'], name='reading_log_shloka__14a205_idx'),
        ),
    ]
