# Generated by Django 4.2.26 on 2025-11-26 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanatan_app', '0002_user_access_token_user_access_token_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('icon', models.TextField(default='🏆')),
                ('condition_type', models.CharField(max_length=50)),
                ('condition_value', models.IntegerField()),
                ('xp_reward', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['condition_value'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='sanatan_app.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='sanatan_app.user')),
            ],
            options={
                'db_table': 'user_achievements',
                'indexes': [models.Index(fields=['user', 'unlocked_at'], name='user_achiev_user_id_40367f_idx')],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shloka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='sanatan_app.shloka')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='sanatan_app.user')),
            ],
            options={
                'db_table': 'favorites',
                'indexes': [models.Index(fields=['user', 'created_at'], name='favorites_user_id_9cc509_idx'), models.Index(fields=['shloka'], name='favorites_shloka__20d322_idx')],
                'unique_together': {('user', 'shloka')},
            },
        ),
    ]
