# Generated by Django 4.2.26 on 2025-11-26 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanatan_app', '0004_chatconversation_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShlokaReadStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marked_read_at', models.DateTimeField(auto_now_add=True)),
                ('last_shown_at', models.DateTimeField(auto_now_add=True)),
                ('shloka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by_users', to='sanatan_app.shloka')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_shlokas', to='sanatan_app.user')),
            ],
            options={
                'db_table': 'shloka_read_status',
                'indexes': [models.Index(fields=['user', 'marked_read_at'], name='shloka_read_user_id_2fa43a_idx'), models.Index(fields=['shloka'], name='shloka_read_shloka__4ca215_idx'), models.Index(fields=['user', 'last_shown_at'], name='shloka_read_user_id_f601e8_idx')],
                'unique_together': {('user', 'shloka')},
            },
        ),
    ]
