# Generated by Django 4.2.26 on 2025-12-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatan_app', '0005_shlokareadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='shlokaexplanation',
            name='context',
            field=models.TextField(blank=True, help_text='Context in the dialogue/story', null=True),
        ),
        migrations.AddField(
            model_name='shlokaexplanation',
            name='modern_examples',
            field=models.JSONField(blank=True, help_text='Modern applications as JSON array', null=True),
        ),
        migrations.AddField(
            model_name='shlokaexplanation',
            name='reflection_prompt',
            field=models.TextField(blank=True, help_text='Question for contemplation', null=True),
        ),
        migrations.AddField(
            model_name='shlokaexplanation',
            name='themes',
            field=models.JSONField(blank=True, help_text='Key themes as JSON array of strings', null=True),
        ),
        migrations.AddField(
            model_name='shlokaexplanation',
            name='why_this_matters',
            field=models.TextField(blank=True, help_text='Modern relevance explanation', null=True),
        ),
        migrations.AddField(
            model_name='shlokaexplanation',
            name='word_by_word',
            field=models.JSONField(blank=True, help_text='Word-by-word breakdown as JSON array', null=True),
        ),
    ]
