# Generated by Django 4.2.26 on 2025-12-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatan_app', '0006_shlokaexplanation_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shlokaexplanation',
            name='word_by_word',
        ),
        migrations.AddField(
            model_name='shloka',
            name='word_by_word',
            field=models.JSONField(blank=True, help_text='Word-by-word breakdown as JSON array', null=True),
        ),
    ]
