# Generated by Django 4.2.26 on 2025-12-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatan_app', '0007_move_word_by_word_to_shloka'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shlokaexplanation',
            name='shloka_expl_shloka__f9555d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='shlokaexplanation',
            unique_together={('shloka',)},
        ),
        migrations.AddField(
            model_name='shlokaexplanation',
            name='detailed_explanation',
            field=models.TextField(blank=True, help_text='Deeper understanding and interpretation', null=True),
        ),
        migrations.AddField(
            model_name='shlokaexplanation',
            name='detailed_meaning',
            field=models.TextField(blank=True, help_text='Core meaning and philosophical significance', null=True),
        ),
        migrations.AddField(
            model_name='shlokaexplanation',
            name='improvement_version',
            field=models.IntegerField(default=0, help_text='Number of improvement iterations performed'),
        ),
        migrations.AddField(
            model_name='shlokaexplanation',
            name='quality_checked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last quality check', null=True),
        ),
        migrations.AddField(
            model_name='shlokaexplanation',
            name='quality_score',
            field=models.IntegerField(default=0, help_text='Overall quality score (0-100)'),
        ),
        migrations.AddField(
            model_name='shlokaexplanation',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief overview of the shloka', null=True),
        ),
        migrations.AlterField(
            model_name='shlokaexplanation',
            name='context',
            field=models.TextField(blank=True, help_text='Context of when/why it was said, context in the dialogue/story', null=True),
        ),
        migrations.AlterField(
            model_name='shlokaexplanation',
            name='modern_examples',
            field=models.JSONField(blank=True, help_text='Modern applications as JSON array of {category, description}', null=True),
        ),
        migrations.AlterField(
            model_name='shlokaexplanation',
            name='themes',
            field=models.JSONField(blank=True, help_text='Key themes/tags as JSON array of strings', null=True),
        ),
        migrations.AlterField(
            model_name='shlokaexplanation',
            name='why_this_matters',
            field=models.TextField(blank=True, help_text='Modern relevance and practical importance', null=True),
        ),
        migrations.AddIndex(
            model_name='shlokaexplanation',
            index=models.Index(fields=['shloka'], name='shloka_expl_shloka__debba5_idx'),
        ),
        migrations.AddIndex(
            model_name='shlokaexplanation',
            index=models.Index(fields=['quality_score'], name='shloka_expl_quality_37d138_idx'),
        ),
        migrations.AddIndex(
            model_name='shlokaexplanation',
            index=models.Index(fields=['quality_checked_at'], name='shloka_expl_quality_d04644_idx'),
        ),
        migrations.RemoveField(
            model_name='shlokaexplanation',
            name='explanation_text',
        ),
        migrations.RemoveField(
            model_name='shlokaexplanation',
            name='explanation_type',
        ),
    ]
