# Generated by Django 4.2.26 on 2025-12-05 10:42

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration is a no-op.
    The unique constraint was already handled in migration 0008 using RunSQL.
    This migration was auto-generated but is redundant.
    """

    dependencies = [
        ('sanatan_app', '0009_remove_shlokaexplanation_shloka_expl_shloka__f9555d_idx'),
    ]

    operations = [
        # No operations needed - unique constraint already handled in 0008
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
