# Generated by Django 4.2.26 on 2025-12-05 10:43

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration is a no-op.
    All operations were already handled in migration 0008.
    This migration was auto-generated but is redundant.
    """

    dependencies = [
        ('sanatan_app', '0010_alter_shlokaexplanation_unique_together'),
    ]

    operations = [
        # No operations needed - everything already handled in 0008
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
