# Generated by Django 4.2.26 on 2025-12-05 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanatan_app', '0011_remove_shlokaexplanation_shloka_expl_shloka__f9555d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0, help_text='Current consecutive days streak', validators=[django.core.validators.MinValueValidator(0)])),
                ('longest_streak', models.IntegerField(default=0, help_text='All-time best streak', validators=[django.core.validators.MinValueValidator(0)])),
                ('streak_freeze_used_this_month', models.BooleanField(default=False, help_text='Whether streak freeze has been used this month')),
                ('last_streak_date', models.DateField(blank=True, help_text='Last date when streak was maintained', null=True)),
                ('total_streak_days', models.IntegerField(default=0, help_text='Lifetime total days with streaks', validators=[django.core.validators.MinValueValidator(0)])),
                ('streak_freeze_reset_date', models.DateField(blank=True, help_text='Date when streak freeze will reset (first day of next month)', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_data', to='sanatan_app.user')),
            ],
            options={
                'db_table': 'user_streaks',
                'indexes': [models.Index(fields=['user'], name='user_streak_user_id_0ea496_idx'), models.Index(fields=['current_streak'], name='user_streak_current_328ca7_idx'), models.Index(fields=['longest_streak'], name='user_streak_longest_5aa820_idx')],
            },
        ),
    ]
