# Generated by Django 4.2.26 on 2025-12-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatan_app', '0012_userstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstreak',
            name='awarded_milestones',
            field=models.JSONField(blank=True, default=list, help_text='List of streak milestone days that have been awarded (e.g., [7, 30, 100, 365])'),
        ),
    ]
